swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /groceries:
    post:
      operationId: groceries.create
      tags:
        - groceries
      summary: Create a grocery item and add it to the shopping list
      description: Create a new grocery in the grocery list
      parameters:
        - name: grocery
          in: body
          description: Item to create
          required: True
          schema:
            type: object
            properties:
              title:
                type: string
                description: Name of grocery to create
      responses:
        201:
          description: Successfully created grocery in list
